### ISSUE TITLE
RSS logo not aligned with header

### ISSUE THREAD

**Issue by siddhss5** [rssrobotics/rssrobotics.github.io#8]
The [RSS logo](https://siddhss5.github.io/images/rsslogo.png) is not alogned with the top header. I tried hard to do this but failed miserably. Someone with greater mastery should attempt!

**Comment by brianhou** [comment]
<img width="1230" alt="screenshot 2016-10-22 13 06 15" src="https://cloud.githubusercontent.com/assets/2406919/19622204/507b0564-9859-11e6-97b2-b3ecae8f0b57.png">

Just to clarify, do you mean that you want to align the two pairs of black lines, either by increasing the size of the text or decreasing the size of the logo?

**Comment by siddhss5** [comment]
Yes! Very nice illustration btw :).
The issue is that they're in two different divs: the image is in the sidebar and the text is in the header, so it's a bit challenging to align them consistently across browsers.

Sidd.

(Rapidly written in motion)

**Comment by brianhou** [comment]
Seems like this is no longer an issue after reverting to the RSS 2016 style?

**Comment by siddhss5** [comment]
Yup!
